### ISSUE TITLE
Les dépendances ne sont pas versionnées

### ISSUE THREAD

**Issue by alexd6631** [musictang/algem#1]
Sauf erreur de ma part, après avoir fait un git clone et une première tentative de compil, la dépendance  `org.apache.commons.codec.binary.Base64` n'est pas résolu. Je suppose qu'il doit manquer le dossier lib/ contenant la dépendence en .jar, ou le pom.xml du projet Maven.

Une solution possible serait donc de commiter les dépendances binaires, soit d'utiliser Maven pour la gestion des dépendances.

Testé sur les branches unstable et 2.9.1

**Comment by alexd6631** [comment]
Pour information, j'ai temporairement résolu le pb, en téléchargeant manuellement la librairie Apache commons codec, mais il serait intéressant à terme de mettre en place une des solutions proposées.

**Comment by musictang** [comment]
Pour l'heure, les dépendances sont incluses dans le dossier zip de l'exécutable : on y trouvera également de la doc utilisateur, des fichiers ressources et les fichiers de conf de démarrage.
