### ISSUE TITLE
Export planning : rendre optionnel l'affichage du membre unique

### ISSUE THREAD

**Issue by alexd6631** [musictang/algem#6]
Actuellement, dans l'export du planning, si un seul membre est inscrit à une plage d'un planning, 
le nom de ce dernier est affiché.

Ce comportement a été introduit dans le commit :
https://github.com/musictang/algem/commit/40eb335242364715985e213c9a76f960139b5308#diff-a6ad52ad810a4c0da4caed8842e1e31fR188

Pour des raisons de clarté et de cohérence, ce comportement n'est pas souhaité par Music Halle. Est t'il envisageable de le rendre optionnel, par exemple avec le système de feature ?

**Comment by musictang** [comment]
Solution : décocher "Afficher le nom des élèves dans les plages de cours individuels" dans les paramètres généraux (Configuration -> Paramètres -> Généraux, rubrique Planning)
